"""日本 TV 「jp_tv_info」行格式：条目列表校验、解析与渲染。"""

from work_catalog_yaml.jp_tv.browse_payload import (
    AnimationTvJpBrowsePresenter,
    JpTvBrowsePresenter,
    build_jp_tv_browse_payload_single_group_order,
    jp_tv_collection_type_profile_key,
    register_jp_tv_browse_presenter,
)
from work_catalog_yaml.jp_tv.load import load_jp_tv_yaml_file
from work_catalog_yaml.jp_tv.parse import (
    JpTvParseError,
    infer_txt_relpath_for_materialize,
    iter_jp_tvinfo_txt_files,
    parse_jp_tv_batch,
    parse_jp_tv_txt_content,
    parse_jp_tv_txt_file,
)
from work_catalog_yaml.jp_tv.render import render_jp_tv_text, render_tag_pairs
from work_catalog_yaml.jp_tv.symbol_table import (
    SymbolKindSpec,
    SymbolValueSpec,
    TvJpSymbolTable,
    builtin_tv_jp_symbol_table,
    clone_tv_jp_symbol_table,
    list_tv_jp_symbol_violations,
    load_tv_jp_symbol_table_yaml,
    merge_tv_jp_symbol_tables,
    merged_tv_jp_symbol_table,
    symbol_table_to_plain_dict,
    tv_jp_symbol_table_from_mapping,
)
from work_catalog_yaml.jp_tv.validate import (
    CatalogAttribute,
    JpTvDocument,
    JpTvEntry,
    append_collection_continuation,
    attribute_to_plain,
    build_tv_jp_entry_attributes,
    entry_air_dates,
    entry_collection_type_data,
    entry_country_slug,
    entry_display_name,
    entry_domain_slug,
    entry_release_type_slug,
    jp_tv_entry_to_plain_dict,
    jp_tv_txt_relpath_from_entry,
    jp_tv_works_to_plain_list,
    load_jp_tv_entries_from_yaml,
    load_jp_tv_yaml_document,
    merge_tv_jp_collect_markers,
    strip_tv_jp_tag_decoration,
    taxonomy_path_segments_from_slugs,
)

__all__ = [
    "AnimationTvJpBrowsePresenter",
    "SymbolKindSpec",
    "SymbolValueSpec",
    "TvJpSymbolTable",
    "builtin_tv_jp_symbol_table",
    "CatalogAttribute",
    "JpTvBrowsePresenter",
    "JpTvDocument",
    "JpTvEntry",
    "JpTvParseError",
    "clone_tv_jp_symbol_table",
    "append_collection_continuation",
    "attribute_to_plain",
    "build_tv_jp_entry_attributes",
    "build_jp_tv_browse_payload_single_group_order",
    "entry_air_dates",
    "entry_collection_type_data",
    "entry_country_slug",
    "entry_display_name",
    "entry_domain_slug",
    "entry_release_type_slug",
    "infer_txt_relpath_for_materialize",
    "iter_jp_tvinfo_txt_files",
    "jp_tv_collection_type_profile_key",
    "jp_tv_entry_to_plain_dict",
    "jp_tv_txt_relpath_from_entry",
    "jp_tv_works_to_plain_list",
    "list_tv_jp_symbol_violations",
    "load_tv_jp_symbol_table_yaml",
    "load_jp_tv_entries_from_yaml",
    "load_jp_tv_yaml_document",
    "load_jp_tv_yaml_file",
    "merge_tv_jp_symbol_tables",
    "merged_tv_jp_symbol_table",
    "merge_tv_jp_collect_markers",
    "parse_jp_tv_batch",
    "parse_jp_tv_txt_content",
    "parse_jp_tv_txt_file",
    "register_jp_tv_browse_presenter",
    "render_jp_tv_text",
    "render_tag_pairs",
    "symbol_table_to_plain_dict",
    "strip_tv_jp_tag_decoration",
    "taxonomy_path_segments_from_slugs",
    "tv_jp_symbol_table_from_mapping",
]
